=== huynguyen0257/XML/PRXProject/web/WEB-INF/xsd/CrawlerConstant.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://huyng/schema/laptop"
            targetNamespace="http://huyng/schema/laptop"
            elementFormDefault="qualified">

    <xsd:element name="pageConstant">
        <xsd:complexType>
            <xsd:all>
                <xsd:element name="domainUrl" type="xsd:string"/>
                <xsd:element name="brandStartSignal" type="xsd:string"/>
                <xsd:element name="brandTagName" type="xsd:string"/>
                <xsd:element name="brandIgnoreText" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="ignoreText" maxOccurs="unbounded" minOccurs="0" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="brandXPath">
                    <xsd:complexType>
                        <xsd:all>
                            <xsd:element name="container" type="xsd:string"/>
                            <xsd:element name="link" type="xsd:string"/>
                            <xsd:element name="name" type="xsd:string"/>
                        </xsd:all>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="pageSizeStartSignal" type="xsd:string"/>
                <xsd:element name="pageSizeTagName" type="xsd:string"/>
                <xsd:element name="pageSizeIgnoreText" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="ignoreText" maxOccurs="unbounded" minOccurs="0" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="pageSizeXPath">
                    <xsd:complexType>
                        <xsd:all>
                            <xsd:element name="allATagWithoutNext" type="xsd:string"/>
                        </xsd:all>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="eachPageStartSignal" type="xsd:string"/>
                <xsd:element name="eachPageTagName" type="xsd:string"/>
                <xsd:element name="eachPageIgnoreText" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="ignoreText" maxOccurs="unbounded" minOccurs="0" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="eachPageXPath">
                    <xsd:complexType>
                        <xsd:all>
                            <xsd:element name="container" type="xsd:string"/>
                            <xsd:element name="link" type="xsd:string"/>
                            <xsd:element name="name" type="xsd:string"/>
                            <xsd:element name="image" type="xsd:string"/>
                            <xsd:element name="price" type="xsd:string"/>
                        </xsd:all>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="detailPageStartSignal" type="xsd:string"/>
                <xsd:element name="detailPageEndSignal" type="xsd:string"/>
                <xsd:element name="detailPageTagName" type="xsd:string"/>
                <xsd:element name="detailPageIgnoreText" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="ignoreText" maxOccurs="unbounded" minOccurs="0" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <xsd:element name="data" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="entity" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="key" type="xsd:string"/>
                                        <xsd:element name="value" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:all>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== huynguyen0257/XML/PRXProject/web/WEB-INF/xmlConstant/IntelCrawlerConstant.xml
<lap:pageConstant xmlns:lap="http://huyng/schema/laptop"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://huyng/schema/laptop ../xsd/CrawlerConstant.xsd">
    <lap:domainUrl>https://www.intel.com</lap:domainUrl>
    <lap:brandStartSignal/>
    <lap:brandTagName/>
    <lap:brandIgnoreText/>
    <lap:brandXPath>
        <lap:container/>
        <lap:link/>
        <lap:name/>
    </lap:brandXPath>

    <lap:pageSizeStartSignal><![CDATA[<span class="paging-info">]]></lap:pageSizeStartSignal>
    <lap:pageSizeTagName>span</lap:pageSizeTagName>
    <lap:pageSizeIgnoreText/>
    <lap:pageSizeXPath>
        <lap:allATagWithoutNext>//span[@class='page-total']</lap:allATagWithoutNext>
    </lap:pageSizeXPath>

    <lap:eachPageStartSignal><![CDATA[<div class="container-wrap card-listings">]]></lap:eachPageStartSignal>
    <lap:eachPageTagName>div</lap:eachPageTagName>
    <lap:eachPageIgnoreText>
        <lap:ignoreText><![CDATA[itemtype.+"]]></lap:ignoreText>
        <lap:ignoreText><![CDATA[itemscope]]></lap:ignoreText>
        <lap:ignoreText><![CDATA[data-picture data-alt="(.+|.?)"]]></lap:ignoreText>
        <lap:ignoreText><![CDATA[<meta.*[^/]>]]></lap:ignoreText>
    </lap:eachPageIgnoreText>
    <lap:eachPageXPath>
        <lap:container>//a[@class='productTitleHref blade-item-link']</lap:container>
        <lap:link>@href</lap:link>
        <lap:name>span</lap:name>
        <lap:image/>
        <lap:price/>
    </lap:eachPageXPath>

    <lap:detailPageStartSignal><![CDATA[<h3 class="tech-heading">Performance</h3>]]></lap:detailPageStartSignal>
    <lap:detailPageEndSignal><![CDATA[<div class="tech-section">]]></lap:detailPageEndSignal>
    <lap:detailPageTagName/>
    <lap:detailPageIgnoreText/>

    <lap:data>
        <lap:entity>
            <lap:key>all_product_page</lap:key>
            <lap:value>https://www.intel.com/content/www/us/en/products/processors/core/view-all.html</lap:value>
        </lap:entity>
    </lap:data>
</lap:pageConstant>

=== huynguyen0257/XML/PRXProject/web/WEB-INF/xmlConstant/PACrawlerConstant.xml
<lap:pageConstant xmlns:lap="http://huyng/schema/laptop"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://huyng/schema/laptop ../xsd/CrawlerConstant.xsd">
    <lap:domainUrl>https://www.phucanh.vn</lap:domainUrl>
    <lap:brandStartSignal><![CDATA[<div class="box-cat">]]></lap:brandStartSignal>
    <lap:brandTagName>div</lap:brandTagName>
    <lap:brandIgnoreText>
        <lap:ignoreText><![CDATA[&nbsp;]]></lap:ignoreText>
    </lap:brandIgnoreText>
    <lap:brandXPath>
        <lap:container>//*[@class='position-relative d-inline-block']/a</lap:container>
        <lap:link>@href</lap:link>
        <lap:name>text()</lap:name>
    </lap:brandXPath>

    <lap:pageSizeStartSignal><![CDATA[<div class="paging">]]></lap:pageSizeStartSignal>
    <lap:pageSizeTagName>div</lap:pageSizeTagName>
    <lap:pageSizeIgnoreText/>
    <lap:pageSizeXPath>
        <lap:allATagWithoutNext>//a[text()!='Tiáº¿p theo']</lap:allATagWithoutNext>
    </lap:pageSizeXPath>

    <lap:eachPageStartSignal><![CDATA[<div class="category-pro-list">]]></lap:eachPageStartSignal>
    <lap:eachPageTagName>div</lap:eachPageTagName>
    <lap:eachPageIgnoreText>
        <lap:ignoreText><![CDATA[&quot;]]></lap:ignoreText>
    </lap:eachPageIgnoreText>
    <lap:eachPageXPath>
        <lap:container>//*[@class='p-container']</lap:container>
        <lap:link>a/@href</lap:link>
        <lap:name>h3[@class='p-name']</lap:name>
        <lap:image>a/img/@data-original</lap:image>
        <lap:price>span[@class='p-price2 ']/text()</lap:price>
    </lap:eachPageXPath>

    <lap:detailPageStartSignal><![CDATA[<div class="tbl-technical nd"]]></lap:detailPageStartSignal>
    <lap:detailPageEndSignal/>
    <lap:detailPageTagName>div</lap:detailPageTagName>
    <lap:detailPageIgnoreText>
        <lap:ignoreText><![CDATA[<p>.*?</p>]]></lap:ignoreText>
    </lap:detailPageIgnoreText>

    <lap:data>
        <lap:entity>
            <lap:key>containerOfAHref</lap:key>
            <lap:value>div</lap:value>
        </lap:entity>
        <lap:entity>
            <lap:key>attributeContainerOfAHref</lap:key>
            <lap:value>class</lap:value>
        </lap:entity>
        <lap:entity>
            <lap:key>valueAttributeContainerOfAHref</lap:key>
            <lap:value>position-relative d-inline-block</lap:value>
        </lap:entity>
        <lap:entity>
            <lap:key>valueAttributeContainerOfAHref</lap:key>
            <lap:value>position-relative d-inline-block</lap:value>
        </lap:entity>
        <lap:entity>
            <lap:key>hrefAttribute</lap:key>
            <lap:value>href</lap:value>
        </lap:entity>
        <lap:entity>
            <lap:key>hrefAttribute</lap:key>
            <lap:value>href</lap:value>
        </lap:entity>
    </lap:data>
</lap:pageConstant>

=== huynguyen0257/XML/PRXProject/web/WEB-INF/xmlConstant/KLCrawlerConstant.xml
<lap:pageConstant xmlns:lap="http://huyng/schema/laptop"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://huyng/schema/laptop ../xsd/CrawlerConstant.xsd">
    <lap:domainUrl>https://kimlongcenter.com</lap:domainUrl>
    <lap:brandStartSignal><![CDATA[<ul id="cate_hori" class="show-menu">]]></lap:brandStartSignal>
    <lap:brandTagName>ul</lap:brandTagName>
    <lap:brandIgnoreText>
        <lap:ignoreText><![CDATA[<img.*[^/]>]]></lap:ignoreText>
        <lap:ignoreText><![CDATA[<a.*_blank">]]></lap:ignoreText>
    </lap:brandIgnoreText>
    <lap:brandXPath>
        <lap:container>//*[@class=' has_child']/a</lap:container>
        <lap:link>@href</lap:link>
        <lap:name>@title</lap:name>
    </lap:brandXPath>

    <lap:pageSizeStartSignal><![CDATA[<ul class="pagination"]]></lap:pageSizeStartSignal>
    <lap:pageSizeTagName>ul</lap:pageSizeTagName>
    <lap:pageSizeIgnoreText>
        <lap:ignoreText><![CDATA[src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="]]></lap:ignoreText>
    </lap:pageSizeIgnoreText>
    <lap:pageSizeXPath>
        <lap:allATagWithoutNext>//li/a[text()!='vàraquo;']</lap:allATagWithoutNext>
    </lap:pageSizeXPath>

    <lap:eachPageStartSignal><![CDATA[<div class="list-product row">]]></lap:eachPageStartSignal>
    <lap:eachPageTagName>div</lap:eachPageTagName>
    <lap:eachPageIgnoreText>
        <lap:ignoreText><![CDATA[src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="]]></lap:ignoreText>
    </lap:eachPageIgnoreText>
    <lap:eachPageXPath>
        <lap:container>//*[@class='product-item']/a</lap:container>
        <lap:link>@href</lap:link>
        <lap:name>div[@class='product-info']/h3/text()</lap:name>
        <lap:image>div[@class='product-img row']/img/@data-src</lap:image>
        <lap:price>div[@class='product-info']/div/p[@class='price']</lap:price>
    </lap:eachPageXPath>

    <lap:detailPageStartSignal><![CDATA[<table class="tbl-info-product">]]></lap:detailPageStartSignal>
    <lap:detailPageEndSignal/>
    <lap:detailPageTagName>table</lap:detailPageTagName>
    <lap:detailPageIgnoreText>
        <lap:ignoreText><![CDATA["™"]]></lap:ignoreText>
        <lap:ignoreText><![CDATA["®"]]></lap:ignoreText>
    </lap:detailPageIgnoreText>
    <lap:data/>
</lap:pageConstant>
